# Generated by Django 4.1.2 on 2022-10-12 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_group', models.UUIDField(default=uuid.UUID('3d161ab7-edad-4a45-b36b-0d38eb8a46b6'))),
                ('chat_id', models.CharField(max_length=100)),
            ],
        ),
    ]
